export const DEFAULT_PLANS = [
    {
        id: 'premium',
        name: 'Premium',
        price: 199,
        currency: 'MXN',
        trialDays: 7,
        durationDays: 0,
        stripePriceId: '',
        description: 'Para profesionales que buscan máxima eficiencia.',
        features: [
            'Paradas ilimitadas',
            'Optimización con Tráfico Real',
            'Historial completo de rutas',
            'Soporte prioritario 24/7',
            'Modo OVNI exclusivo',
        ],
        highlight: true,
        active: true,
        order: 1,
        color: 'from-info via-blue-500 to-indigo-600',
        cta: 'Prueba 7 días gratis',
        ctaLink: '',
    },
    {
        id: 'fleet',
        name: 'Flotilla',
        price: 899,
        currency: 'MXN',
        trialDays: 0,
        durationDays: 0,
        stripePriceId: '',
        description: 'Control total de tu flota y choferes con planes a medida.',
        features: [
            'Precios especiales para flotillas',
            'Contratos por tiempo personalizado',
            'Monitoreo GPS en vivo de flota',
            'Reportes de rendimiento por chofer',
            'API para integraciones empresariales',
        ],
        highlight: false,
        active: true,
        order: 2,
        color: 'from-purple-500 to-pink-600',
        cta: 'Probar ahora',
        ctaLink: '',
    },
];
